# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: sm-pkg

env_files:
  github_token: /run/secrets/github_token

before:
  hooks:
    - rustup default nightly
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    binary: sm-pkg
    flags:
      - --release
      - --package=sm-pkg-bin
    targets:
      - x86_64-unknown-linux-gnu
      #- x86_64-pc-windows-gnu

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: sm-pkg
    name: sm-pkg
  draft: false
  replace_existing_draft: true
  use_existing_draft: true
  replace_existing_artifacts: true
